### ISSUE TITLE
Speed up docker image for Mac and Windows OS

### ISSUE THREAD

**Issue by APshenkin** [butomo1989/docker-android#11]
I tried the docker image on Mac.
Emulator needs more than 15 minutes to start.

Is there any way to speed up emulator loading?

BTW locally without docker emulator starts very fast

Thanks in advance

**Comment by andrcuns** [comment]
On linux it starts in about 30-40 seconds. I think even with arm images it should not take 15 minutes to start for sure.

**Comment by butomo1989** [comment]
Hi @APshenkin,

This issue is known. Unfortunately for Mac and Windows you need to use arm image like @andrcuns mentioned because HAXM doesn't work on linux. To be able to get the fastest speed, you need to use x86 image that works only on Linux OS. arm image takes normally around 10 minutes to make emulator ready and x86 takes around 10-40 seconds depends on your processor and RAM, e.g. in my laptop it takes around 10 seconds. 

I will let this issue open and investigate if I can speed up docker image for Mac and Windows OS.

**Comment by andrcuns** [comment]
Don't know much about the issue since I don't have a Mac, but is this problem specifically related to docker or to x86 images in general?
Judging from [this](https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-mac-os-x), one should be able to run x86 on OSX.

**Comment by butomo1989** [comment]
I think the issue is on android itself. OSX and Windows use HAXM and Linux use KVM to be able to use x86 system image. And because we put android inside Docker, we can only use KVM and the installation feature of HAXM doesn't exist in Android SDK Manager.  
<img width="660" alt="haxm doesnt work in docker" src="https://cloud.githubusercontent.com/assets/22218312/26560472/2b524760-44b7-11e7-9b80-be7ee5a775a6.png">

**Comment by andrcuns** [comment]
I see @butomo1989 Actually good to know. I have developed mobile testing capability using these images and need to make some notes that it won't be of much use locally on macs.

**Comment by butomo1989** [comment]
but I will investigate further @andrcuns . There might be a way to solve this issue.

**Comment by QAutomatron** [comment]
And what about use a `docker-machine create --driver virtualbox` under mac, what images should i use inside virtual machine, same arm as on regular mac host? Is there any options to emulate kvm-linux image under mac?

**Comment by butomo1989** [comment]
Hi @QAutomatron,

You still need to use arm image, because docker-machine / virtual box do not support virtualisation as far as I remember. And regarding emulate kvm under Mac I tried it last time and it didn't work. :(

**Comment by APshenkin** [comment]
@butomo1989 FYI, I'm able to create x86 emulator using Android studio on Mac and it works perfect, but, when trying to start docker image with x86 emulator, it crashes on start up.

**Comment by andrcuns** [comment]
It's like @butomo1989 said, in container you have linux environment which doesn't have HAXM support and at the moment doesn't look like it's possible to install it in container or to somehow map KVM to HAXM or something like that.

**Comment by butomo1989** [comment]
x86 can be run under VM #17 with ESXi. I won't longer support arm image in the future. I will try it with virtualbox.

**Comment by butomo1989** [comment]
see: https://github.com/butomo1989/docker-android/issues/17#issuecomment-311963259
