### ISSUE TITLE
Android crash after running some app

### ISSUE THREAD

**Issue by Scisaga** [butomo1989/docker-android#15]
As you click app icon, the flash screen is loaded, and then android crash and back to boot screen. no log printed.

Step 1, click app icon:
![image 1](https://user-images.githubusercontent.com/4192865/27282188-827f7722-5521-11e7-9b13-071b3edf6a76.png)

Step 2, flash screen is loaded:
![image 2](https://user-images.githubusercontent.com/4192865/27282205-90cd5aa6-5521-11e7-8c99-ab70d97f7df0.png)

Step 3, android creash and back to boot screen, no log printed.
![image 3](https://user-images.githubusercontent.com/4192865/27282225-9afe8f40-5521-11e7-9a2f-e9baa02fa51c.png)

**Comment by butomo1989** [comment]
Hi @Scisaga ,

Sorry for late response and thank you for reporting this issue. could you maybe check target sdk of your app? or retry with other emulators with different android version? because I think it might be because your app do not support that version.

the log should be printed with following command:
`docker exec -it android-container tail -f /var/log/supervisor/docker-android.stdout.log`

**Comment by butomo1989** [comment]
I'll close this issue because there is no further response. Please feel free to reopen this issue.
