### ISSUE TITLE
Emulator on the images get stuck and need to be killed

### ISSUE THREAD

**Issue by oxygen220** [butomo1989/docker-android#16]
Hi,

I have tried almost all linux and Windows images but unfortunally emulator get stuck while container is running an then I should kill its process.  No matter how much resource is dedicated to Docker.

OS: Windows 10

**Comment by butomo1989** [comment]
Hi @oxygen220 ,

Thank you for reporting this issue. what do you mean with "get stuck"? could you can send me the error message? you can get it with following command: 
`docker exec -it android-container tail -f /var/log/supervisor/docker-android.stdout.log`
But I think it is not an error, you just need to wait bit longer because you can only arm image on windows OS and it takes around 10 minutes to get emulator ready. I will try to find way to speed up it for Mac and Windows OS (you can follow this issue #11 ). For best performance, you need to use linux OS for it.

**Comment by oxygen220** [comment]
Thanks, That 's duplicate of #11
