### ISSUE TITLE
emulator first time boot is about 20 minutes

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#23]
Hi 
the performance of docker especially the first time docker started is very slow and it takes about 20 minutes to start emulator
.
i have tested android 5.1 , 6  and 7.1.
my host is ubuntu 16 on digitalocean with 4cpu and 8G memory.

this is host VXT:
kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

docker ps show docker unhealthly about 20 minutes

**Comment by butomo1989** [comment]
Hi @mehrdad-abdoli , 

thank you for opening this issue. could you join https://gitter.im/butomo1989/docker-android? we can discuss there so I will close this issue, because I think this issue is not related to the docker-image that I've already provided in README.md. I assume it might be other reason. but if it is because of the docker image, we can reopen this issue.

**Comment by ciekawy** [comment]
I wonder if there was any conclusion on this one. Just tried to run `docker-android` on DO droplet yet have same experience of super slow execution. Was even able to deploy and launch an app yet everything seem to be some 20-50x slower than it should be ;)
I know this may be related to the KVM, womdering if there are any chances to improve the performance in simiar setup, ideally for DO

**Comment by ciekawy** [comment]
one thing I found thanks to https://www.blackhatworld.com/seo/script-turn-your-linux-vps-server-into-windows-server-automatically-using-shell-script.1097732/ is that `nested=1` parameter passed to the kvm module makes a difference as only after adding this I am getting
```
$cat /sys/module/kvm_intel/parameters/nested
Y
```

I think it makes also just some difference to the performance - it is still poor but a bit better. I hope there may be some other steps to improve it further
