### ISSUE TITLE
install libhoudini to translate arm apps to x86

### ISSUE THREAD

**Issue by otoniel-isidoro** [butomo1989/docker-android#39]
The number of apps compatible with the x86 emulator is very limited. 
I tried the libhoudini to translate the arm apps to x86 but without success! 
https://android.stackexchange.com/questions/179482/android-emulator-install-failed-no-matching-abis-failed-to-extract-native-lib
Can anyone help me with this?

**Comment by butomo1989** [comment]
Hi @otoniel-isidoro ,

Thank you for opening this issue but I will close this issue, because docker-android wont support a conversion of apk from arm to x86. You could ask the developer to provide x86 apk. the other alternative you need to use arm docker image.
Please feel free to reopen this issue if there is an approach how to solve this issue.
