### ISSUE TITLE
butomo1989/docker-android-x86-7.1.1 tries to connect to Selenium grid even if launched without

### ISSUE THREAD

**Issue by laurainwebo** [butomo1989/docker-android#50]
I launched the docker image butomo1989/docker-android-x86-7.1.1 without the options to attach to a Selenium hub yet clearly in my appium server console window it is trying to attach to a hub.

Would it be possible to update the appium images to the latest version 1.7.1?

**Comment by butomo1989** [comment]
Hi @laurainwebo ,

Thank you for the issue. 
you can find in the [readme](https://github.com/butomo1989/docker-android/blob/master/README.md) how to attach that image with to selenium hub. you can join [this group chat](https://gitter.im/butomo1989/docker-android) if you need any help.

about the latest version of Appium (1.7.1) is in the release branch 0.9 and I am still working on it. I will release it in few days. 

I will close this issue because it is not a bug but feel free to reopen it if there is any other issue.
