### ISSUE TITLE
docker-appium as base image

### ISSUE THREAD

**Issue by butomo1989** [butomo1989/docker-android#9]
Using docker-appium as base image https://github.com/appium/appium-docker-android/tree/master/Appium. It will be implemented after release of new version of docker-appium.

**Comment by butomo1989** [comment]
delete libgconf-2-4 from docker-android as soon as docker-appium is used as a base image. see: https://github.com/appium/appium-docker-android/pull/38

**Comment by andrcuns** [comment]
Me and my chromedriver issues again :D One thing to consider, since docker-appium uses latest appium version, it comes with a pretty recent, most likely latest chromedriver versions which causes issues when running against even latest 7.1.1 android image since by default it has chrome 53 if I'm not mistaken which is a bit too old for latest chromedriver. One option would be add ability with to start appium with custom chromedriver executable which is achieved with `--chromedriver-executable` option.

**Comment by butomo1989** [comment]
thank you for this info @andrcuns!

**Comment by andrcuns** [comment]
Added PR #12 to help with potential problem described above.

**Comment by butomo1989** [comment]
Done on release [0.7](https://github.com/butomo1989/docker-android/releases/tag/0.7)
