### ISSUE TITLE
Able to switch locale / language on the fly

### ISSUE THREAD

**Issue by butomo1989** [butomo1989/docker-android#90]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/butomo1989/docker-android). Thank you!**

## Expected Behavior
It should be possible to change locale on fly by passing environment variable

## Actual Behavior
It do not have that feature right now (you need to modify it from setting if you want to change the language)

**Comment by JoeSSS** [comment]
I'm not sure if it is a good idea at all.. but what we're doing right now is archiving the whole `android_emulator` folder and apply it on the image. This gives us instant boot (because the snapshots are also copying over) and also possibility to add stuff to emulator (language/none animation/contacts/store credentials etc.).

**Comment by butomo1989** [comment]
@JoeSSS I think it is not a good idea, because the changes inside Emulator (for example in Settings) will be stored that as well. but there is no harm if you can add it in the documentation and create a PR maybe? I assume that you use the existing android_emulator folder from host and share volume with docker container, right?

**Comment by butomo1989** [comment]
Fixed in [release-1.3-p3](https://github.com/butomo1989/docker-android/releases/tag/1.3-p3)
